export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const SET_QUIZ_STATE = 'SET_QUIZ_STATE';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const NEXT_QUIZ_QUESTION = 'NEXT_QUIZ_QUESTION';
export const RETRY_QUIZ = 'RETRY_QUIZ';
